version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: app-laravel-docker
        container_name: app-techlint-gateway
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - db
            - redis

    webserver:
        image: nginx:alpine
        container_name: nginx-techlint-gateway
        restart: unless-stopped
        ports:
            - "54000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: postgres-techlint-gateway
        restart: unless-stopped
        ports:
            - "54001:5432"
        environment:
            POSTGRES_DB: gateway
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret123
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis-techlint-gateway
        restart: unless-stopped
        ports:
            - "54002:6379"
        networks:
            - laravel

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        image: app-laravel-docker
        container_name: queue-techlint-gateway
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: php artisan queue:listen --verbose --tries=3 --timeout=90 # use queue:work for production
        depends_on:
            - app
            - redis
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
