version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: app-laravel-docker
        container_name: app-techlint-gateway
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - db
            - redis

    webserver:
        image: nginx:alpine
        container_name: nginx-techlint-gateway
        restart: unless-stopped
        ports:
            - "54000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: postgres-techlint-gateway
        restart: unless-stopped
        ports:
            - "54001:5432"
        environment:
            POSTGRES_DB: gateway
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret123
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: redis-techlint-gateway
        restart: unless-stopped
        ports:
            - "54002:6379"
        networks:
            - laravel

    # scheduler:
    #     image: laravel-app
    #     container_name: laravel-scheduler
    #     restart: unless-stopped
    #     working_dir: /var/www
    #     volumes:
    #         - ./:/var/www
    #     command: |
    #         sh -c "while [ true ]; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
    #     networks:
    #         - laravel
    #     depends_on:
    #         - app

    # queue:
    #     image: laravel-app
    #     container_name: laravel-queue
    #     restart: unless-stopped
    #     working_dir: /var/www
    #     volumes:
    #         - ./:/var/www
    #     command: php artisan queue:work --verbose --tries=3 --timeout=90
    #     networks:
    #         - laravel
    #     depends_on:
    #         - app
    #         - redis

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
